openapi: 3.0.1
info:
  title: Translation Service US Azure OpenAI Service API
  description: Azure OpenAI APIs for completions and search
  version: '1.0'
servers:
  - url: https://api.developer.nielseniq.com/cis/us/translation/openai
paths:
  '/deployments/{deployment-id}/chat/completions':
    post:
      summary: Creates a completion for the chat message
      description: Creates a completion for the chat message
      operationId: 688cd23dbe4114127cd8747c
      parameters:
        - name: deployment-id
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              temperature: 1
              top_p: 1
              stream: false
              stop: ''
              max_tokens: 4096
              presence_penalty: 0
              frequency_penalty: 0
              logit_bias: { }
              user: user-1234
              messages:
                - role: system
              data_sources:
                - type: azure_search
              n: 1
              seed: 0
              response_format:
                type: text
              tools:
                - type: function
                  function:
                    description: string
                    name: string
                    parameters: { }
              tool_choice: { }
              functions:
                - name: string
                  description: string
                  parameters: { }
              function_call: { }
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                id: string
                object: chat.completion
                created: 0
                model: string
                usage:
                  prompt_tokens: 0
                  completion_tokens: 0
                  total_tokens: 0
                system_fingerprint: string
                prompt_filter_results:
                  - prompt_index: 0
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      jailbreak:
                        filtered: true
                        detected: true
                choices:
                  - index: 0
                    finish_reason: string
                    message:
                      role: assistant
                      content: string
                      tool_calls:
                        - id: string
                          type: function
                          function:
                            name: string
                            arguments: string
                      function_call:
                        name: string
                        arguments: string
                      context:
                        citations:
                          - content: string
                            title: string
                            url: string
                            filepath: string
                            chunk_id: string
                        intent: string
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      protected_material_text:
                        filtered: true
                        detected: true
                      protected_material_code:
                        filtered: true
                        detected: true
                        citation:
                          URL: string
                          license: string
        '400':
          description: Service unavailable
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      jailbreak:
                        filtered: true
                        detected: true
                  code: string
                  message: string
        '500':
          description: Service unavailable
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      jailbreak:
                        filtered: true
                        detected: true
                  code: string
                  message: string
  '/deployments/{deployment-id}/completions':
    post:
      summary: 'Creates a completion for the provided prompt, parameters and chosen model'
      description: 'Creates a completion for the provided prompt, parameters and chosen model.'
      operationId: 688cd23dbe4114127cd8747d
      parameters:
        - name: deployment-id
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              prompt: "Negate the following sentence.The price for bubblegum increased on thursday.\n\n Negated Sentence:"
              max_tokens: 50
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                model: davinci
                object: text_completion
                id: cmpl-4509KAos68kxOqpE2uYGw81j6m7uo
                created: 1637097562
                choices:
                  - index: 0
                    text: The price for bubblegum decreased on thursday.
                    logprobs: ''
                    finish_reason: stop
        '400':
          description: Service unavailable
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      jailbreak:
                        filtered: true
                        detected: true
                  code: string
                  message: string
        '500':
          description: Service unavailable
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      error:
                        code: string
                        message: string
                      jailbreak:
                        filtered: true
                        detected: true
                  code: string
                  message: string
  '/deployments/{deployment-id}/embeddings':
    post:
      summary: Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms. (Discover)
      description: Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms.
      operationId: 688cd23dbe4114127cd8747e
      parameters:
        - name: deployment-id
          in: path
          description: The deployment id of the model which was deployed.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              input: { }
              user: string
              input_type: query
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                object: string
                model: string
                data:
                  - index: 0
                    object: string
                    embedding:
                      - 0
                usage:
                  prompt_tokens: 0
                  total_tokens: 0
  /batches:
    get:
      summary: Gets a list of all batches owned by the Azure OpenAI resource.
      operationId: 688cd23dbe4114127cd8747f
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
        - name: after
          in: query
          description: Identifier for the last event from the previous pagination request.
          schema:
            type: string
        - name: limit
          in: query
          description: Number of batches to retrieve. Defaults to 20.
          schema:
            enum:
              - 20
            type: integer
            default: 20
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
    post:
      summary: "Creates and executes a batch from an uploaded file of requests.\r\nResponse includes details of the enqueued job including job status.\r\nThe ID of the result file is added to the response once complete."
      operationId: 688cd23dbe4114127cd87480
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      requestBody:
        description: The specification of the batch to create and execute.
        content:
          application/json:
            example:
              input_file_id: string
              endpoint: string
              completion_window: string
              metadata: { }
      responses:
        '200':
          description: The batch has been successfully created.
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/batches/{batch-id}':
    get:
      summary: Gets details for a single batch specified by the given batch-id.
      operationId: 688cd23dbe4114127cd87481
      parameters:
        - name: batch-id
          in: path
          description: The identifier of the batch.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/batches/{batch-id}/cancel':
    post:
      summary: Cancels the processing of the batch specified by the given batch-id.
      operationId: 688cd23dbe4114127cd87482
      parameters:
        - name: batch-id
          in: path
          description: The identifier of the batch.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The batch has been successfully canceled.
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  /files:
    get:
      summary: "Gets a list of all files owned by the Azure OpenAI resource.\r\nThese include user uploaded content like files with purpose \"fine-tune\" for training or validation of fine-tunes models\r\nas well as files that are generated by the service such as \"fine-tune-results\" which contains various metrics for the"
      operationId: 688cd23dbe4114127cd87483
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
        - name: purpose
          in: query
          description: Only return files with the given purpose.
          schema:
            enum:
              - fine-tune
              - fine-tune-results
              - assistants
              - assistants_output
              - batch
              - batch_output
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
    post:
      summary: 'Creates a new file entity by uploading data from a local machine. Uploaded files can, for example, be used for training or evaluating fine-tuned models.'
      operationId: 688cd23dbe4114127cd87484
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '201':
          description: The file has been successfully created.
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/files/{file-id}':
    get:
      summary: 'Gets details for a single file specified by the given file-id including status, size, purpose, etc.'
      operationId: 688cd23dbe4114127cd87485
      parameters:
        - name: file-id
          in: path
          description: The identifier of the file.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/files/{file-id}/content':
    get:
      summary: "Gets the content of the file specified by the given file-id.\r\nFiles can be user uploaded content or generated by the service like result metrics of a fine-tune job."
      operationId: 688cd23dbe4114127cd87486
      parameters:
        - name: file-id
          in: path
          description: The identifier of the file.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/octet-stream: { }
        '400':
          description: An error occurred.
          content:
            application/octet-stream: { }
  /files/import:
    post:
      summary: 'Creates a new file entity by importing data from a provided url. Uploaded files can, for example, be used for training or evaluating fine-tuned models.'
      operationId: 688cd23dbe4114127cd87487
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      requestBody:
        description: 'The definition of the file to create including its purpose, the file name and the url of the file location.'
        content:
          application/json: { }
      responses:
        '201':
          description: The file has been successfully created.
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  /fine_tuning/jobs:
    get:
      summary: "Gets a list of all fine-tune jobs owned by the Azure OpenAI resource.\r\nThe details that are returned for each fine-tune job contain besides its identifier\r\nthe base model, training and validation files, hyper parameters, time stamps, status and events.\r\nEvents are created when the job status changes"
      operationId: 688cd23dbe4114127cd87488
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
        - name: after
          in: query
          description: Identifier for the last event from the previous pagination request.
          schema:
            type: string
        - name: limit
          in: query
          description: Number of events to retrieve. Defaults to 20.
          schema:
            enum:
              - 20
            type: integer
            default: 20
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/fine_tuning/jobs/{fine-tuning-job-id}':
    get:
      summary: "Gets details for a single fine-tune job specified by the given fine-tune-id.\r\nThe details contain the base model, training and validation files, hyper parameters, time stamps, status and events.\r\nEvents are created when the job status changes, e.g. running or complete, and when results are uploaded."
      operationId: 688cd23dbe4114127cd87489
      parameters:
        - name: fine-tuning-job-id
          in: path
          description: The identifier of the fine-tune job.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
    delete:
      summary: Deletes the fine-tune job specified by the given fine-tune-id.
      operationId: 688cd23dbe4114127cd8748a
      parameters:
        - name: fine-tuning-job-id
          in: path
          description: The identifier of the fine-tune job.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The fine tune was successfully deleted.
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/fine_tuning/jobs/{fine-tuning-job-id}/events':
    get:
      summary: "Gets the events for the fine-tune job specified by the given fine-tune-id.\r\nEvents are created when the job status changes, e.g. running or complete, and when results are uploaded."
      operationId: 688cd23dbe4114127cd8748b
      parameters:
        - name: fine-tuning-job-id
          in: path
          description: The identifier of the fine-tune job.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
        - name: after
          in: query
          description: Identifier for the last event from the previous pagination request.
          schema:
            type: string
        - name: limit
          in: query
          description: Number of events to retrieve. Defaults to 20.
          schema:
            enum:
              - 20
            type: integer
            default: 20
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/fine_tuning/jobs/{fine-tuning-job-id}/cancel':
    post:
      summary: Cancels the processing of the fine-tune job specified by the given fine-tune-id.
      operationId: 688cd23dbe4114127cd8748c
      parameters:
        - name: fine-tuning-job-id
          in: path
          description: The identifier of the fine-tune job.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The fine tune has been successfully canceled
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/fine_tuning/jobs/{fine-tuning-job-id}/checkpoints':
    get:
      summary: "Gets the checkpoints for the fine-tune job specified by the given fine-tune-id.\r\nCheckpoints are created at the end of successful epochs during training."
      operationId: 688cd23dbe4114127cd8748d
      parameters:
        - name: fine-tuning-job-id
          in: path
          description: The identifier of the fine-tune job.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
        - name: after
          in: query
          description: Identifier for the last checkpoint ID from the previous pagination request.
          schema:
            type: string
        - name: limit
          in: query
          description: Number of checkpoints to retrieve. Defaults to 10.
          schema:
            enum:
              - 10
            type: integer
            default: 10
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  /models:
    get:
      summary: "Gets a list of all models that are accessible by the Azure OpenAI resource.\r\nThese include base models as well as all successfully completed fine-tuned models owned by the Azure OpenAI resource."
      operationId: 688cd23dbe4114127cd8748e
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/models/{model-id}':
    get:
      summary: Gets details for the model specified by the given modelId.
      operationId: 688cd23dbe4114127cd8748f
      parameters:
        - name: model-id
          in: path
          description: The identifier of the model.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  /uploads:
    post:
      summary: "An intermediate Upload object is created, allowing you to add Parts to it. Currently, an Upload size can be a maximum of 9 GB in total and will expire two hours after being created.\r\nAfter the Upload is completed a File object will be generated, containing all the uploaded parts. This File object ca"
      operationId: 688cd23dbe4114127cd87490
      parameters:
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      requestBody:
        description: The definition of the file to create including its purpose and the location on the local machine.
        content:
          application/json: { }
      responses:
        '200':
          description: The upload has been successfully created.
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/uploads/{upload-id}/parts':
    post:
      summary: "Adds a Part to an Upload object, where each Part represents a segment of the file you are uploading.\r\nEach Part can be up to the standard size limit for file upload, based on the File Purpose. You can continue adding Parts until reaching the Upload size limit of 9 GB."
      operationId: 688cd23dbe4114127cd87491
      parameters:
        - name: upload-id
          in: path
          description: The identifier of the upload.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/uploads/{upload-id}/complete':
    post:
      summary: "This completes the Upload, and the returned Upload object contains a nested File object that is ready for use across the platform.\r\nYou can define the order of the Parts by providing an ordered list of Part IDs.\r\nThe total number of bytes uploaded must match the size originally specified when creati"
      operationId: 688cd23dbe4114127cd87492
      parameters:
        - name: upload-id
          in: path
          description: The identifier of the upload.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      requestBody:
        description: The definition of the file to create including its purpose and the location on the local machine.
        content:
          application/json:
            example:
              part_ids:
                - string
              md5: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/uploads/{upload-id}/cancel':
    post:
      summary: "Cancels the Upload, and will lead to all uploaded parts to be deleted asynchronously.\r\nNo Parts may be added after an Upload is cancelled."
      operationId: 688cd23dbe4114127cd87493
      parameters:
        - name: upload-id
          in: path
          description: The identifier of the upload.
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          description: The requested API version.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: { }
        '400':
          description: An error occurred.
          content:
            application/json: { }
  '/deployments/{deployment-id}/images/generations':
    post:
      summary: Generates a batch of images from a text caption on a given DALLE model deployment
      description: Generates a batch of images from a text caption on a given DALLE model deployment
      operationId: 688cd23dbe4114127cd87494
      parameters:
        - name: deployment-id
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              prompt: a corgi in a field
              n: 1
              size: 1024x1024
              response_format: url
              user: user123456
              quality: standard
              style: vivid
      responses:
        '200':
          description: Ok
          content:
            application/json:
              example:
                created: '1676540381'
                data:
                  - url: https://www.contoso.com
                    b64_json: string
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                    revised_prompt: string
                    prompt_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      jailbreak:
                        filtered: true
                        detected: true
        '400':
          description: An error occurred.
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      jailbreak:
                        filtered: true
                        detected: true
                    revised_prompt: string
                  code: string
                  message: string
        '500':
          description: An error occurred.
          content:
            application/json:
              example:
                error:
                  param: string
                  type: string
                  inner_error:
                    code: ResponsibleAIPolicyViolation
                    content_filter_results:
                      sexual:
                        filtered: true
                        severity: safe
                      violence:
                        filtered: true
                        severity: safe
                      hate:
                        filtered: true
                        severity: safe
                      self_harm:
                        filtered: true
                        severity: safe
                      profanity:
                        filtered: true
                        detected: true
                      jailbreak:
                        filtered: true
                        detected: true
                    revised_prompt: string
                  code: string
                  message: string
  '/deployments/{deployment-id}/audio/translations':
    post:
      summary: Transcribes and translates input audio into English text.
      description: Transcribes and translates input audio into English text.
      operationId: 688cd23dbe4114127cd87495
      parameters:
        - name: deployment-id
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                prompt:
                  type: string
                response_format:
                  enum:
                    - json
                    - text
                    - srt
                    - verbose_json
                    - vtt
                  type: string
                  description: AudioResponseFormat
                temperature:
                  enum:
                    - '0'
                  type: string
                  default: '0'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                text: string
            text/plain: { }
  '/deployments/{deployment-id}/audio/transcriptions':
    post:
      summary: Transcribes audio into the input language.
      description: Transcribes audio into the input language.
      operationId: 688cd23dbe4114127cd87496
      parameters:
        - name: deployment-id
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                prompt:
                  type: string
                response_format:
                  enum:
                    - json
                    - text
                    - srt
                    - verbose_json
                    - vtt
                  type: string
                  description: AudioResponseFormat
                temperature:
                  enum:
                    - '0'
                  type: string
                  default: '0'
                language:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                text: string
            text/plain: { }
components: { }